In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import  nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent =['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'i am a good developer',
      'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'your videos are good']

In [8]:
#size of dictonary
voc_size=10000

## One hot representation

In [12]:
onehot_rep=[one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[3056, 3043, 1584, 5040], [3056, 3043, 1584, 7366], [3056, 8143, 1584, 8006], [8214, 81, 9890, 1, 6230], [8214, 81, 9890, 1, 581], [9729, 5954, 3656, 1]]


In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

## Word Embedding Representation

#### Pad Sequencing 

     For representing the data using word embedding all the sentence size should be same. so we use pad sequeencing.

In [13]:
sent_len=8
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_len)

In [14]:
print(embedded_docs)

[[   0    0    0    0 3056 3043 1584 5040]
 [   0    0    0    0 3056 3043 1584 7366]
 [   0    0    0    0 3056 8143 1584 8006]
 [   0    0    0 8214   81 9890    1 6230]
 [   0    0    0 8214   81 9890    1  581]
 [   0    0    0    0 9729 5954 3656    1]]


In [16]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
